### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Aviksaikat** [pinterest/pinterest-python-sdk#115]
```
from pinterest.organic.pins import Pin
ModuleNotFoundError: No module named 'pinterest.organic'; 'pinterest' is not a package
```
 
**Additional Details (please complete the following information):**
 
 - OS and Version: Linux Kali GNU/Linux Rolling
 - SDK Version : Python3.9

**Additional Context**
I'm using poetry and installed  the package
```toml
[tool.poetry.dependencies]
pinterest-api-sdk = "^0.2.1"
```
